openapi: 3.0.3
info:
  title: JobQuest Geolocation-Based Job Mapping API
  version: 1.0.0
  description: |
    API for geolocation-based job discovery, map integration, and job filtering.
    Part of JobQuest Navigator Epic 1.
    
    **Note:** Currently, only Adzuna is supported as the external job source. The API is designed for future extensibility.

servers:
  - url: http://localhost:8000
    description: Local Development

tags:
  - name: Job Search
    description: APIs for discovering and filtering job opportunities

paths:
  /api/jobs:
    get:
      tags: [Job Search]
      summary: Retrieve Job Listings
      description: |
        Fetch job listings based on user location and filters. Supports geolocation-based job mapping.
        **Currently, only Adzuna is supported as the job data source.**
      parameters:
        - in: query
          name: latitude
          schema:
            type: number
            format: float
          required: false
          description: User's latitude for geolocation-based filtering.
        - in: query
          name: longitude
          schema:
            type: number
            format: float
          required: false
          description: User's longitude for geolocation-based filtering.
        - in: query
          name: radius
          schema:
            type: integer
            default: 50
          required: false
          description: Search radius in miles (default is 50 miles).
        - in: query
          name: keyword
          schema:
            type: string
          required: false
          description: Keyword to filter jobs by title or description.
      responses:
        '200':
          description: Successful response with a list of job listings.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
                  count:
                    type: integer
                    example: 25
        '400':
          description: Invalid request parameters (e.g., invalid latitude/longitude).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Invalid latitude or longitude values.
        '500':
          description: Server error (e.g., failed to fetch data from external API).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Internal server error.
      security:
        - bearerAuth: []

components:
  schemas:
    Job:
      type: object
      properties:
        id:
          type: string
          example: job_12345
          description: Unique identifier for the job listing.
        title:
          type: string
          example: Software Engineer
          description: Job title.
        company:
          type: string
          example: TechCorp
          description: Company name.
        location:
          type: string
          example: London, UK
          description: Job location.
        latitude:
          type: number
          format: float
          example: 51.5074
          description: Latitude of job location.
        longitude:
          type: number
          format: float
          example: -0.1278
          description: Longitude of job location.
        postedAt:
          type: string
          format: date-time
          example: 2023-10-15T12:00:00Z
          description: Date and time the job was posted (ISO 8601).
        sourceApi:
          type: string
          example: Adzuna
          description: Source API of the job listing (currently only Adzuna).
      required:
        - id
        - title
        - company
        - location
        - postedAt
        - sourceApi

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token required for authenticated requests.
