# Generated by Django 4.2.23 on 2025-06-23 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(help_text='Company overview and key information')),
                ('culture_analysis', models.TextField(help_text='Company culture and work environment analysis')),
                ('recent_news', models.TextField(blank=True, help_text='Recent company news and updates')),
                ('financial_highlights', models.TextField(blank=True, help_text='Financial performance and highlights')),
                ('growth_prospects', models.TextField(blank=True, help_text='Growth opportunities and future outlook')),
                ('research_date', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in research accuracy (0-1)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-research_date'],
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_type', models.CharField(choices=[('mock_interview', 'Mock Interview'), ('question_practice', 'Question Practice'), ('company_prep', 'Company-Specific Prep')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('completion_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('self_rating', models.PositiveIntegerField(blank=True, help_text='User self-rating (1-5)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Session notes and reflections')),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('session_data', models.JSONField(default=dict, help_text='Detailed session data (questions, answers, timings)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('behavioral', 'Behavioral'), ('company_specific', 'Company-Specific')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('position_type', models.CharField(blank=True, max_length=100)),
                ('sample_answer', models.TextField(blank=True, help_text='Sample answer or guidance')),
                ('answer_framework', models.TextField(blank=True, help_text='Framework for answering (e.g., STAR method)')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='core.company')),
            ],
            options={
                'ordering': ['question_type', 'difficulty', 'question_text'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position_title', models.CharField(blank=True, max_length=255)),
                ('key_talking_points', models.TextField(help_text='Important points to discuss')),
                ('company_specific_prep', models.TextField(help_text='Company-specific preparation notes')),
                ('technical_focus_areas', models.TextField(blank=True, help_text='Technical areas to focus on')),
                ('behavioral_scenarios', models.TextField(blank=True, help_text='Behavioral interview scenarios')),
                ('preparation_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('company_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_prep', to='company_research.companyresearch')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('insight_type', models.CharField(choices=[('culture', 'Company Culture'), ('interview_process', 'Interview Process'), ('compensation', 'Compensation & Benefits'), ('work_life_balance', 'Work-Life Balance'), ('growth_opportunities', 'Growth Opportunities'), ('team_dynamics', 'Team Dynamics')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, help_text='Source of the insight', max_length=255)),
                ('credibility_score', models.FloatField(default=0.5, help_text='Credibility score (0-1)')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this research')),
                ('tags', models.JSONField(default=list, help_text='User-defined tags for organization')),
                ('company_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='company_research.companyresearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'company_research')},
            },
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('published_date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('relevance_score', models.FloatField(default=0.0, help_text='Relevance for job seekers (0-1)')),
                ('categories', models.JSONField(default=list, help_text='News categories (e.g., hiring, funding, product launches)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='core.company')),
            ],
            options={
                'ordering': ['-published_date'],
                'unique_together': {('company', 'url')},
            },
        ),
    ]
