# Generated by Django 4.2.23 on 2025-06-24 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_job_contract_type_category_job_category'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Application Screening'), ('phone_screening', 'Phone Screening'), ('technical_interview', 'Technical Interview'), ('behavioral_interview', 'Behavioral Interview'), ('final_interview', 'Final Interview'), ('reference_check', 'Reference Check'), ('offer_pending', 'Offer Pending'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='applied', max_length=50)),
                ('previous_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('screening', 'Application Screening'), ('phone_screening', 'Phone Screening'), ('technical_interview', 'Technical Interview'), ('behavioral_interview', 'Behavioral Interview'), ('final_interview', 'Final Interview'), ('reference_check', 'Reference Check'), ('offer_pending', 'Offer Pending'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], max_length=50)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('application_source', models.CharField(blank=True, help_text='Where did you apply? (company website, LinkedIn, etc.)', max_length=100)),
                ('cover_letter_used', models.TextField(blank=True)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_response_date', models.DateField(blank=True, null=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this application')),
                ('contacts', models.TextField(blank=True, help_text='Contact person details (JSON format)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_details', to='jobs.jobapplication')),
                ('resume_version', models.ForeignKey(help_text='The specific resume version used for this application', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='resumes.resumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('screening', 'Application Screening'), ('phone_screening', 'Phone Screening'), ('technical_interview', 'Technical Interview'), ('behavioral_interview', 'Behavioral Interview'), ('final_interview', 'Final Interview'), ('reference_check', 'Reference Check'), ('offer_pending', 'Offer Pending'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], max_length=50)),
                ('to_status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Application Screening'), ('phone_screening', 'Phone Screening'), ('technical_interview', 'Technical Interview'), ('behavioral_interview', 'Behavioral Interview'), ('final_interview', 'Final Interview'), ('reference_check', 'Reference Check'), ('offer_pending', 'Offer Pending'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this status change')),
                ('application_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='application_tracking.applicationtracker')),
            ],
            options={
                'verbose_name_plural': 'Application status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('status_update', 'Status Update'), ('interview_reminder', 'Interview Reminder'), ('follow_up_reminder', 'Follow-up Reminder'), ('deadline_reminder', 'Deadline Reminder'), ('custom', 'Custom')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App Notification'), ('both', 'Both Email and In-App')], default='in_app', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='application_tracking.applicationtracker')),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('applications_by_status', models.JSONField(default=dict)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('interview_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('offer_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_time_to_response_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_time_to_interview_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('most_successful_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_metrics', to='resumes.resumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Interview'), ('in_person', 'In-Person Interview'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('panel', 'Panel Interview'), ('group', 'Group Interview'), ('final', 'Final Interview')], max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('meeting_link', models.URLField(blank=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=200)),
                ('interviewer_title', models.CharField(blank=True, max_length=200)),
                ('interviewer_email', models.EmailField(blank=True, max_length=254)),
                ('preparation_notes', models.TextField(blank=True)),
                ('post_interview_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('self_rating', models.PositiveIntegerField(blank=True, help_text='Rate your performance 1-10', null=True)),
                ('feedback_received', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='application_tracking.applicationtracker')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio'), ('certificate', 'Certificate'), ('transcript', 'Transcript'), ('reference', 'Reference Letter'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.FileField(upload_to='application_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='application_tracking.applicationtracker')),
            ],
        ),
        migrations.AddIndex(
            model_name='applicationtracker',
            index=models.Index(fields=['user', 'status'], name='application_user_id_46fcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtracker',
            index=models.Index(fields=['user', 'priority'], name='application_user_id_79b366_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtracker',
            index=models.Index(fields=['applied_date'], name='application_applied_2b290e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtracker',
            index=models.Index(fields=['next_follow_up_date'], name='application_next_fo_c47f43_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtracker',
            index=models.Index(fields=['is_favorite'], name='application_is_favo_ebf744_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnotification',
            index=models.Index(fields=['application_tracker', 'is_sent'], name='application_applica_664e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnotification',
            index=models.Index(fields=['scheduled_for'], name='application_schedul_628954_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnotification',
            index=models.Index(fields=['is_read'], name='application_is_read_0aecaa_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationmetrics',
            index=models.Index(fields=['user', 'period_start', 'period_end'], name='application_user_id_3bac7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationmetrics',
            unique_together={('user', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='applicationinterview',
            index=models.Index(fields=['application_tracker', 'status'], name='application_applica_71573b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationinterview',
            index=models.Index(fields=['scheduled_date'], name='application_schedul_28e31f_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application_tracker', 'document_type'], name='application_applica_1b7c0f_idx'),
        ),
    ]
