#!/bin/bash

# JobQuest Navigator - Release Packaging Script
# This script packages the entire prod directory for distribution

set -e  # Exit on any error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Default values
VERSION="1.0.0"
OUTPUT_DIR="../release"
PACKAGE_NAME="jobquest-navigator-production"

# Function to show usage
show_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -v, --version VERSION     Release version (default: $VERSION)"
    echo "  -o, --output DIR          Output directory (default: $OUTPUT_DIR)"
    echo "  -n, --name NAME           Package name (default: $PACKAGE_NAME)"
    echo "  -h, --help               Show this help message"
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -v|--version)
            VERSION="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -n|--name)
            PACKAGE_NAME="$2"
            shift 2
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
done

print_status "Starting JobQuest Navigator Release Packaging..."
print_status "Version: $VERSION"
print_status "Package Name: $PACKAGE_NAME"
print_status "Output Directory: $OUTPUT_DIR"

# Create timestamp
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
FULL_PACKAGE_NAME="${PACKAGE_NAME}-v${VERSION}-${TIMESTAMP}"

# Create output directory
mkdir -p "$OUTPUT_DIR"
RELEASE_DIR="$OUTPUT_DIR/$FULL_PACKAGE_NAME"

print_status "Creating release directory: $RELEASE_DIR"
mkdir -p "$RELEASE_DIR"

# =============================================================================
# Copy Production Files
# =============================================================================

print_status "Copying production files..."

# Copy main directories
print_status "Copying backend code..."
cp -r ../backend "$RELEASE_DIR/"

print_status "Copying frontend code..."
cp -r ../frontend "$RELEASE_DIR/"

print_status "Copying infrastructure templates..."
cp -r ../infrastructure "$RELEASE_DIR/"

print_status "Copying configuration files..."
cp -r ../configs "$RELEASE_DIR/"

print_status "Copying documentation..."
cp -r ../docs "$RELEASE_DIR/"

print_status "Copying scripts..."
cp -r ../scripts "$RELEASE_DIR/"

# Create tests directory structure
mkdir -p "$RELEASE_DIR/tests"
if [ -d "../tests" ]; then
    cp -r ../tests/* "$RELEASE_DIR/tests/"
fi

# =============================================================================
# Generate Release Information
# =============================================================================

print_status "Generating release information..."

# Create release info file
cat > "$RELEASE_DIR/RELEASE_INFO.md" << EOF
# JobQuest Navigator Production Release

**Version**: $VERSION  
**Build Date**: $(date)  
**Build ID**: $TIMESTAMP  

## Package Contents

- \`backend/\` - Django REST API backend code
- \`frontend/\` - React frontend application
- \`infrastructure/\` - AWS CloudFormation templates
- \`configs/\` - Configuration files and environment templates
- \`docs/\` - Complete documentation set
- \`scripts/\` - Deployment and management scripts
- \`tests/\` - Test suites and validation scripts

## Quick Start

1. **Prerequisites**:
   - AWS CLI configured
   - Python 3.9+
   - Node.js 18+
   - Docker (optional, for local testing)

2. **Configuration**:
   \`\`\`bash
   cd configs/
   cp environment.env .env
   # Edit .env with your AWS configuration
   \`\`\`

3. **Deploy Infrastructure**:
   \`\`\`bash
   cd scripts/
   ./deploy-infrastructure.sh
   \`\`\`

4. **Deploy Backend**:
   \`\`\`bash
   cd backend/
   ../scripts/deploy-backend.sh
   \`\`\`

5. **Deploy Frontend**:
   \`\`\`bash
   cd frontend/
   ../scripts/deploy-frontend.sh
   \`\`\`

6. **Verify Deployment**:
   \`\`\`bash
   cd scripts/
   ./verify-deployment.sh
   \`\`\`

## Documentation

- **Deployment Guide**: docs/DEPLOYMENT_GUIDE.md
- **Architecture Overview**: docs/JobQuest_Navigator_AWS_Deployment_Architecture.md
- **Troubleshooting**: docs/TROUBLESHOOTING_GUIDE.md
- **API Documentation**: Check backend/docs/ for API specs

## Support

For issues and questions:
- Check troubleshooting guide
- Review CloudWatch logs
- Contact development team

---
*Generated by JobQuest Navigator Release Packaging System*
EOF

# Create checksums file
print_status "Generating checksums..."
cd "$RELEASE_DIR"
find . -type f -exec sha256sum {} \; > CHECKSUMS.txt
cd - > /dev/null

# =============================================================================
# Clean Up Sensitive Files
# =============================================================================

print_status "Cleaning up sensitive files..."

# Remove sensitive files and directories
find "$RELEASE_DIR" -name "*.pyc" -delete
find "$RELEASE_DIR" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find "$RELEASE_DIR" -name ".env" -delete 2>/dev/null || true
find "$RELEASE_DIR" -name "*.log" -delete 2>/dev/null || true
find "$RELEASE_DIR" -name ".DS_Store" -delete 2>/dev/null || true
find "$RELEASE_DIR" -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true
find "$RELEASE_DIR" -name "venv" -type d -exec rm -rf {} + 2>/dev/null || true
find "$RELEASE_DIR" -name ".git" -type d -exec rm -rf {} + 2>/dev/null || true

# Remove development databases
rm -f "$RELEASE_DIR/backend/db.sqlite3" 2>/dev/null || true
rm -f "$RELEASE_DIR/backend/db_local.sqlite3" 2>/dev/null || true

# Remove temporary files
rm -rf "$RELEASE_DIR/backend/staticfiles" 2>/dev/null || true
rm -rf "$RELEASE_DIR/frontend/build" 2>/dev/null || true
rm -rf "$RELEASE_DIR/frontend/dist" 2>/dev/null || true

# =============================================================================
# Create Installation Script
# =============================================================================

print_status "Creating installation script..."

cat > "$RELEASE_DIR/install.sh" << 'EOF'
#!/bin/bash

# JobQuest Navigator - Installation Script
# This script helps with initial setup and configuration

set -e

echo "========================================"
echo "JobQuest Navigator Installation Script"
echo "========================================"
echo

# Check prerequisites
echo "Checking prerequisites..."

if ! command -v aws &> /dev/null; then
    echo "ERROR: AWS CLI not found. Please install AWS CLI first."
    exit 1
fi

if ! command -v python &> /dev/null; then
    echo "ERROR: Python not found. Please install Python 3.9+ first."
    exit 1
fi

if ! command -v node &> /dev/null; then
    echo "ERROR: Node.js not found. Please install Node.js 18+ first."
    exit 1
fi

if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo "ERROR: AWS CLI not configured. Please run 'aws configure' first."
    exit 1
fi

echo "✓ Prerequisites check passed"
echo

# Setup configuration
echo "Setting up configuration..."

if [ ! -f "configs/.env" ]; then
    if [ -f "configs/environment.env" ]; then
        cp configs/environment.env configs/.env
        echo "✓ Created configs/.env from template"
        echo "⚠ Please edit configs/.env with your AWS configuration before proceeding"
    else
        echo "ERROR: Configuration template not found"
        exit 1
    fi
else
    echo "✓ Configuration file already exists"
fi

# Make scripts executable
echo "Making scripts executable..."
chmod +x scripts/*.sh
echo "✓ Scripts are now executable"

echo
echo "========================================"
echo "Installation completed successfully!"
echo "========================================"
echo
echo "Next steps:"
echo "1. Edit configs/.env with your AWS configuration"
echo "2. Run: scripts/deploy-infrastructure.sh"
echo "3. Run: scripts/deploy-backend.sh"
echo "4. Run: scripts/deploy-frontend.sh"
echo "5. Run: scripts/verify-deployment.sh"
echo
echo "For detailed instructions, see docs/DEPLOYMENT_GUIDE.md"
EOF

chmod +x "$RELEASE_DIR/install.sh"

# =============================================================================
# Create Documentation Index
# =============================================================================

print_status "Creating documentation index..."

cat > "$RELEASE_DIR/README.md" << EOF
# JobQuest Navigator - Production Release v$VERSION

Welcome to the JobQuest Navigator production deployment package. This is a complete AWS-ready deployment package for the JobQuest Navigator job search and career management platform.

## 🚀 Quick Start

1. **Install Prerequisites**:
   - AWS CLI (configured with appropriate credentials)
   - Python 3.9+
   - Node.js 18+

2. **Run Installation Script**:
   \`\`\`bash
   ./install.sh
   \`\`\`

3. **Configure Environment**:
   \`\`\`bash
   # Edit configuration file
   nano configs/.env
   \`\`\`

4. **Deploy to AWS**:
   \`\`\`bash
   # Deploy infrastructure
   scripts/deploy-infrastructure.sh
   
   # Deploy backend
   scripts/deploy-backend.sh
   
   # Deploy frontend
   scripts/deploy-frontend.sh
   
   # Verify deployment
   scripts/verify-deployment.sh
   \`\`\`

## 📁 Package Structure

\`\`\`
jobquest-navigator-production/
├── README.md                 # This file
├── RELEASE_INFO.md          # Release information
├── CHECKSUMS.txt            # File integrity checksums
├── install.sh               # Installation helper script
├── backend/                 # Django REST API
├── frontend/                # React application
├── infrastructure/          # AWS CloudFormation templates
├── configs/                 # Configuration templates
├── docs/                    # Complete documentation
├── scripts/                 # Deployment scripts
└── tests/                   # Test suites
\`\`\`

## 📖 Documentation

| Document | Description |
|----------|-------------|
| [Deployment Guide](docs/DEPLOYMENT_GUIDE.md) | Complete deployment instructions |
| [Architecture Overview](docs/JobQuest_Navigator_AWS_Deployment_Architecture.md) | System architecture and design |
| [Troubleshooting Guide](docs/TROUBLESHOOTING_GUIDE.md) | Common issues and solutions |

## 🛠️ Available Scripts

| Script | Purpose |
|--------|---------|
| \`install.sh\` | Initial setup and configuration |
| \`scripts/deploy-infrastructure.sh\` | Deploy AWS infrastructure |
| \`scripts/deploy-backend.sh\` | Deploy Django backend to Lambda |
| \`scripts/deploy-frontend.sh\` | Deploy React frontend to S3 |
| \`scripts/verify-deployment.sh\` | Verify all components are working |
| \`scripts/package-release.sh\` | Create release packages |

## 🏗️ Architecture

JobQuest Navigator uses a modern serverless architecture on AWS:

- **Frontend**: React SPA hosted on S3 with CloudFront
- **Backend**: Django REST API running on Lambda with API Gateway
- **Database**: MySQL on RDS
- **Storage**: S3 for static files and media
- **Monitoring**: CloudWatch for logs and metrics

## 💰 Cost Estimation

Monthly cost estimate for production deployment:
- **RDS MySQL (db.t3.micro)**: ~\$15
- **Lambda**: ~\$2 (1M requests)
- **API Gateway**: ~\$3 (1M requests)
- **S3**: ~\$0.12 (5GB storage)
- **Data Transfer**: ~\$0.90 (10GB)
- **Total**: ~\$21/month

## 🔒 Security Features

- VPC isolation for database
- IAM roles with least privilege
- S3 bucket policies for secure access
- CORS configuration for frontend-backend communication
- Environment variables for sensitive configuration

## 🧪 Testing

The package includes comprehensive test suites:
- Infrastructure validation tests
- API endpoint tests
- Frontend functionality tests
- Integration tests
- Performance benchmarks

## 📞 Support

For support and questions:
1. Check the troubleshooting guide
2. Review CloudWatch logs
3. Consult the documentation
4. Contact the development team

## 📝 License

This project is for educational purposes as part of a graduation project.

---

**Release Version**: $VERSION  
**Build Date**: $(date)  
**Package ID**: $TIMESTAMP
EOF

# =============================================================================
# Create Archive
# =============================================================================

print_status "Creating release archive..."

cd "$OUTPUT_DIR"

# Create tar.gz archive
ARCHIVE_NAME="${FULL_PACKAGE_NAME}.tar.gz"
tar -czf "$ARCHIVE_NAME" "$FULL_PACKAGE_NAME"

# Create zip archive for Windows compatibility
ZIP_NAME="${FULL_PACKAGE_NAME}.zip"
zip -r "$ZIP_NAME" "$FULL_PACKAGE_NAME" > /dev/null

cd - > /dev/null

# =============================================================================
# Generate Release Summary
# =============================================================================

print_status "Generating release summary..."

# Calculate sizes
ARCHIVE_SIZE=$(du -h "$OUTPUT_DIR/$ARCHIVE_NAME" | cut -f1)
ZIP_SIZE=$(du -h "$OUTPUT_DIR/$ZIP_NAME" | cut -f1)
DIR_SIZE=$(du -sh "$RELEASE_DIR" | cut -f1)

# Count files
FILE_COUNT=$(find "$RELEASE_DIR" -type f | wc -l)

# Create release summary
SUMMARY_FILE="$OUTPUT_DIR/RELEASE_SUMMARY.txt"
cat > "$SUMMARY_FILE" << EOF
JobQuest Navigator Production Release Summary
============================================

Release Information:
  Version: $VERSION
  Build Date: $(date)
  Build ID: $TIMESTAMP
  Package Name: $FULL_PACKAGE_NAME

Package Statistics:
  Directory Size: $DIR_SIZE
  Archive Size (tar.gz): $ARCHIVE_SIZE
  Archive Size (zip): $ZIP_SIZE
  Total Files: $FILE_COUNT

Package Contents:
  - Backend Django application with all dependencies
  - Frontend React application (source code)
  - AWS CloudFormation infrastructure templates
  - Configuration templates and examples
  - Complete documentation set
  - Deployment and management scripts
  - Test suites and validation tools

Deployment Options:
  1. Extract and run install.sh for guided setup
  2. Manual deployment using individual scripts
  3. CI/CD integration using provided scripts

Support Files:
  - README.md: Quick start guide
  - RELEASE_INFO.md: Detailed release information
  - CHECKSUMS.txt: File integrity verification
  - install.sh: Automated setup script

Archives Created:
  - ${ARCHIVE_NAME} (Linux/macOS)
  - ${ZIP_NAME} (Windows/Universal)

Next Steps:
  1. Distribute the archive files
  2. Users should extract and run install.sh
  3. Follow the deployment guide in docs/
  4. Use verify-deployment.sh to validate

Generated by: JobQuest Navigator Release System
EOF

# =============================================================================
# Final Report
# =============================================================================

print_success "Release packaging completed successfully!"
echo
echo "================================================================================"
echo "                           RELEASE PACKAGE SUMMARY"
echo "================================================================================"
echo
echo "Package Information:"
echo "  Name: $FULL_PACKAGE_NAME"
echo "  Version: $VERSION"
echo "  Build Date: $(date)"
echo "  Directory Size: $DIR_SIZE"
echo "  Total Files: $FILE_COUNT"
echo
echo "Created Files:"
echo "  📁 Release Directory: $RELEASE_DIR"
echo "  📦 Tar Archive: $OUTPUT_DIR/$ARCHIVE_NAME ($ARCHIVE_SIZE)"
echo "  📦 Zip Archive: $OUTPUT_DIR/$ZIP_NAME ($ZIP_SIZE)"
echo "  📄 Summary: $SUMMARY_FILE"
echo
echo "Package Contents:"
echo "  ✓ Backend application (Django REST API)"
echo "  ✓ Frontend application (React SPA)"
echo "  ✓ Infrastructure templates (CloudFormation)"
echo "  ✓ Configuration templates"
echo "  ✓ Complete documentation"
echo "  ✓ Deployment scripts"
echo "  ✓ Test suites"
echo "  ✓ Installation helper"
echo
echo "Distribution Ready:"
echo "  ✓ Archives created and ready for distribution"
echo "  ✓ Checksums generated for integrity verification"
echo "  ✓ Documentation complete"
echo "  ✓ Installation scripts included"
echo
echo "Next Steps:"
echo "  1. Test the package by extracting and running install.sh"
echo "  2. Distribute archives to deployment teams"
echo "  3. Provide users with README.md for quick start"
echo "  4. Keep RELEASE_SUMMARY.txt for records"
echo

print_success "JobQuest Navigator v$VERSION production release is ready!"

# Save package info for reference
echo "$FULL_PACKAGE_NAME" > "$OUTPUT_DIR/LATEST_RELEASE.txt"