openapi: 3.0.3
info:
  title: JobQuest Resume Management & AI Suggestion API
  version: 1.0.0
  description: |
    API for automated resume versioning, AI-driven suggestion engine, and file management.
    Part of JobQuest Navigator Epic 2.

servers:
  - url: http://localhost:8000
    description: Local Development

tags:
  - name: Resume
    description: Resume upload, versioning, and management
  - name: AI Suggestion
    description: AI-powered resume recommendation and feedback
  - name: File
    description: File upload, download, and management

paths:
  /api/resumes:
    post:
      tags: [Resume]
      summary: Upload a new resume
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                name:
                  type: string
                  example: "Kevin_Resume.pdf"
      responses:
        '201':
          description: Resume uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resume'
        '400':
          $ref: '#/components/responses/BadRequest'
    get:
      tags: [Resume]
      summary: List all resumes for the current user
      responses:
        '200':
          description: List of resumes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resume'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/resumes/{resumeId}:
    get:
      tags: [Resume]
      summary: Get a specific resume and its versions
      parameters:
        - in: path
          name: resumeId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resume details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resume'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [Resume]
      summary: Delete a resume
      parameters:
        - in: path
          name: resumeId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Resume deleted

  /api/resumes/{resumeId}/versions:
    get:
      tags: [Resume]
      summary: List all versions of a resume
      parameters:
        - in: path
          name: resumeId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of resume versions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResumeVersion'

    post:
      tags: [Resume]
      summary: Upload a new version for a resume
      parameters:
        - in: path
          name: resumeId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                comment:
                  type: string
      responses:
        '201':
          description: New version uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeVersion'

  /api/suggestions:
    post:
      tags: [AI Suggestion]
      summary: Get AI recommendation for a resume and job description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resumeId:
                  type: string
                jobDescription:
                  type: string
      responses:
        '200':
          description: AI suggestion result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Suggestion'
        '400':
          $ref: '#/components/responses/BadRequest'

    get:
      tags: [AI Suggestion]
      summary: List AI suggestions for the current user
      responses:
        '200':
          description: List of suggestions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Suggestion'

  /api/files/{fileId}:
    get:
      tags: [File]
      summary: Download a file (resume)
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File download
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [File]
      summary: Delete a file
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: File deleted

components:
  schemas:
    Resume:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        userId:
          type: string
        createdAt:
          type: string
          format: date-time
        versions:
          type: array
          items:
            $ref: '#/components/schemas/ResumeVersion'
    ResumeVersion:
      type: object
      properties:
        id:
          type: string
        resumeId:
          type: string
        fileId:
          type: string
        createdAt:
          type: string
          format: date-time
        comment:
          type: string
    Suggestion:
      type: object
      properties:
        id:
          type: string
        resumeId:
          type: string
        jobDescription:
          type: string
        score:
          type: number
          format: float
        feedback:
          type: string
        createdAt:
          type: string
          format: date-time

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
