# Generated by Django 4.2.23 on 2025-06-17 02:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('business', 'Business'), ('creative', 'Creative'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('general', 'General')], max_length=20)),
                ('description', models.TextField()),
                ('template_data', models.JSONField(help_text='Template structure and styling')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='resume_templates/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resumes_template',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['category'], name='resumes_tem_categor_e18d0f_idx'), models.Index(fields=['is_active'], name='resumes_tem_is_acti_0dc238_idx'), models.Index(fields=['is_premium'], name='resumes_tem_is_prem_cfc5ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('professional_summary', models.TextField(blank=True)),
                ('resume_data', models.JSONField(default=dict, help_text='Complete resume data structure')),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('target_industry', models.CharField(blank=True, max_length=50)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_modified_section', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resumetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes_resume',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('resume_data', models.JSONField()),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'db_table': 'resumes_version',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['resume', 'version_number'], name='resumes_ver_resume__65887d_idx')],
                'unique_together': {('resume', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ResumeSkillMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(blank=True, max_length=50)),
                ('relevance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_primary_skill', models.BooleanField(default=False)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('found_in_section', models.CharField(blank=True, max_length=50)),
                ('context_snippet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_matches', to='resumes.resume')),
            ],
            options={
                'db_table': 'resumes_skill_match',
                'ordering': ['-relevance_score', 'skill_name'],
                'indexes': [models.Index(fields=['resume', 'relevance_score'], name='resumes_ski_resume__5dd34f_idx'), models.Index(fields=['skill_category'], name='resumes_ski_skill_c_f87569_idx')],
                'unique_together': {('resume', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='ResumeShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with_email', models.EmailField(max_length=254)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('comment', 'View & Comment'), ('edit', 'View & Edit')], default='view', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='resumes.resume')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes_share',
                'indexes': [models.Index(fields=['share_token'], name='resumes_sha_share_t_8f66d5_idx'), models.Index(fields=['shared_with_email'], name='resumes_sha_shared__7ba205_idx')],
                'unique_together': {('resume', 'shared_with_email')},
            },
        ),
        migrations.CreateModel(
            name='ResumeExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('html', 'HTML'), ('txt', 'Plain Text')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('include_photo', models.BooleanField(default=True)),
                ('include_references', models.BooleanField(default=True)),
                ('custom_styling', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resumes.resume')),
            ],
            options={
                'db_table': 'resumes_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resume', 'format'], name='resumes_exp_resume__f92ce6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumeComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resumecomment')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resumes.resume')),
            ],
            options={
                'db_table': 'resumes_comment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['resume', 'created_at'], name='resumes_com_resume__a46f35_idx'), models.Index(fields=['author_email'], name='resumes_com_author__ec593f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'status'], name='resumes_res_user_id_3262c5_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['target_role'], name='resumes_res_target__f8118c_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['target_industry'], name='resumes_res_target__0a4524_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['is_default'], name='resumes_res_is_defa_173de3_idx'),
        ),
    ]
