# Generated by Django 4.2.23 on 2025-06-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_research_update',
        ),
        migrations.RemoveField(
            model_name='company',
            name='research_data',
        ),
        migrations.AddField(
            model_name='company',
            name='ai_research_data',
            field=models.JSONField(blank=True, help_text='Stores the structured company research data from the AI service, matching the CompanyResearch schema.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_research_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful research generation.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_research_model',
            field=models.CharField(blank=True, help_text='The AI model used for the last research generation (e.g., gpt-4o).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_research_prompt_version',
            field=models.CharField(blank=True, help_text='The prompt version used for the last research generation (e.g., company_research_v1).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_research_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NONE', 'None')], db_index=True, default='NONE', help_text='The current status of the AI research generation for this company.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['ai_research_status'], name='companies_ai_rese_547d27_idx'),
        ),
    ]
