# Generated by Django 4.2.23 on 2025-06-23 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('suggestion_type', models.CharField(choices=[('resume_improvement', 'Resume Improvement'), ('job_match', 'Job Match Recommendation'), ('keyword_optimization', 'Keyword Optimization'), ('format_suggestion', 'Format Suggestion'), ('content_enhancement', 'Content Enhancement'), ('skill_highlight', 'Skill Highlighting'), ('experience_optimization', 'Experience Optimization')], max_length=50)),
                ('prompt_template', models.TextField(help_text='Template for AI prompt with placeholders')),
                ('context_fields', models.JSONField(default=list, help_text='Required context fields for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_suggestion_templates',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['suggestion_type'], name='ai_suggesti_suggest_3b3d1d_idx'), models.Index(fields=['is_active'], name='ai_suggesti_is_acti_73100b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('resume_improvement', 'Resume Improvement'), ('job_match', 'Job Match Recommendation'), ('keyword_optimization', 'Keyword Optimization'), ('format_suggestion', 'Format Suggestion'), ('content_enhancement', 'Content Enhancement'), ('skill_highlight', 'Skill Highlighting'), ('experience_optimization', 'Experience Optimization')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggestion_content', models.JSONField(help_text='Structured suggestion data')),
                ('ai_model', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('custom-model', 'Custom Model')], default='gpt-3.5-turbo', max_length=50)),
                ('confidence_score', models.FloatField(help_text='AI confidence in this suggestion (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to generate (seconds)', null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Context used to generate suggestion')),
                ('target_job_id', models.UUIDField(blank=True, help_text='Related job posting ID', null=True)),
                ('target_resume_id', models.UUIDField(blank=True, help_text='Related resume ID', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partially_accepted', 'Partially Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('acted_on_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_suggestions', to='ai_suggestions.suggestiontemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AILearningData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('suggestion_feedback', 'Suggestion Feedback'), ('user_behavior', 'User Behavior'), ('job_match_outcome', 'Job Match Outcome'), ('resume_update', 'Resume Update')], max_length=50)),
                ('input_data', models.JSONField(help_text='Input used for AI')),
                ('output_data', models.JSONField(help_text='AI output')),
                ('ground_truth', models.JSONField(blank=True, help_text='Actual user action/outcome', null=True)),
                ('performance_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('is_training_data', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_learning_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['data_type'], name='ai_learning_data_ty_95dc5a_idx'), models.Index(fields=['is_training_data'], name='ai_learning_is_trai_21f0eb_idx'), models.Index(fields=['created_at'], name='ai_learning_created_908e19_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuggestionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('irrelevant', 'Irrelevant'), ('excellent', 'Excellent'), ('needs_improvement', 'Needs Improvement')], max_length=20)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('accuracy_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('relevance_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('usefulness_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('implemented', models.BooleanField(default=False)),
                ('implementation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_suggestions.aisuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_suggestion_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feedback_type'], name='ai_suggesti_feedbac_45991a_idx'), models.Index(fields=['rating'], name='ai_suggesti_rating_54b69e_idx'), models.Index(fields=['implemented'], name='ai_suggesti_impleme_1f35a0_idx')],
                'unique_together': {('suggestion', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SuggestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_type', models.CharField(choices=[('daily_suggestions', 'Daily Suggestions'), ('job_match_analysis', 'Job Match Analysis'), ('resume_optimization', 'Resume Optimization'), ('skill_recommendations', 'Skill Recommendations')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_suggestions', models.PositiveIntegerField(default=0)),
                ('successful_suggestions', models.PositiveIntegerField(default=0)),
                ('failed_suggestions', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_suggestion_batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ai_suggesti_user_id_c8a705_idx'), models.Index(fields=['batch_type'], name='ai_suggesti_batch_t_2e675f_idx'), models.Index(fields=['created_at'], name='ai_suggesti_created_b46406_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumeJobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_id', models.UUIDField(help_text='Resume ID being analyzed')),
                ('job_id', models.UUIDField(help_text='Job ID being matched against')),
                ('overall_match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('skills_match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('experience_match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('keyword_match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('matching_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('suggested_improvements', models.JSONField(default=list)),
                ('strength_areas', models.JSONField(default=list)),
                ('weakness_areas', models.JSONField(default=list)),
                ('ai_model', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('custom-model', 'Custom Model')], default='gpt-3.5-turbo', max_length=50)),
                ('analysis_summary', models.TextField()),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_resume_job_matches',
                'ordering': ['-overall_match_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'resume_id'], name='ai_resume_j_user_id_49a97f_idx'), models.Index(fields=['overall_match_score'], name='ai_resume_j_overall_6c2da2_idx'), models.Index(fields=['created_at'], name='ai_resume_j_created_a4d300_idx')],
                'unique_together': {('user', 'resume_id', 'job_id')},
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(help_text='Related job posting ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('match_score', models.FloatField(help_text='How well the job matches the user (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recommendation_reason', models.TextField(help_text='Why this job was recommended')),
                ('matching_skills', models.JSONField(default=list, help_text='Skills that match')),
                ('missing_skills', models.JSONField(default=list, help_text='Skills user needs to develop')),
                ('ai_model', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('custom-model', 'Custom Model')], default='gpt-3.5-turbo', max_length=50)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('viewed', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_job_recommendations',
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'viewed'], name='ai_job_reco_user_id_8e0a6f_idx'), models.Index(fields=['match_score'], name='ai_job_reco_match_s_f53a39_idx'), models.Index(fields=['created_at'], name='ai_job_reco_created_7763fa_idx')],
                'unique_together': {('user', 'job_id')},
            },
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['user', 'status'], name='ai_suggesti_user_id_824322_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['suggestion_type'], name='ai_suggesti_suggest_4e1e65_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['created_at'], name='ai_suggesti_created_150c89_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['confidence_score'], name='ai_suggesti_confide_ea8822_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['target_job_id'], name='ai_suggesti_target__db4eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['target_resume_id'], name='ai_suggesti_target__5fe328_idx'),
        ),
    ]
